import {
  KrakenWebsocketBase,
  KrakenWsMethodResponseEnvelope,
} from '../../../base/websocketBase';

export type KrakenWsOrderSide = 'buy' | 'sell';

export type KrakenWsOrderType =
  | 'limit'
  | 'market'
  | 'iceberg'
  | 'stop-loss'
  | 'stop-loss-limit'
  | 'take-profit'
  | 'take-profit-limit'
  | 'trailing-stop'
  | 'trailing-stop-limit'
  | 'settle-position';

export type KrakenWsTriggerReference = 'index' | 'last';
export type KrakenWsPriceType = 'static' | 'pct' | 'quote';
export type KrakenWsTimeInForce = 'gtc' | 'gtd' | 'ioc';
export type KrakenWsFeePreference = 'base' | 'quote';
export type KrakenWsStpType = 'cancel_newest' | 'cancel_oldest' | 'cancel_both';

/**
 * Trigger parameters for triggered order types.
 */
export interface KrakenWsAddOrderTriggers {
  /**
   * Reference price to track for triggering orders.
   * Default is "last".
   */
  reference?: KrakenWsTriggerReference;

  /**
   * Amount for the trigger price (static or relative).
   */
  price: number;

  /**
   * Units for the trigger price. Default is "static".
   */
  price_type?: KrakenWsPriceType;
}

/**
 * Conditional template for secondary close orders (OTO).
 */
export interface KrakenWsAddOrderConditional {
  /**
   * Order type of the secondary close orders.
   */
  order_type:
    | 'limit'
    | 'stop-loss'
    | 'stop-loss-limit'
    | 'take-profit'
    | 'take-profit-limit'
    | 'trailing-stop'
    | 'trailing-stop-limit';

  /**
   * Limit price for secondary orders that support a limit price.
   */
  limit_price?: number;

  /**
   * Units for the limit price on the secondary orders.
   * Only available for trailing-stop-limit.
   */
  limit_price_type?: KrakenWsPriceType;

  /**
   * Trigger price amount for secondary orders (static or relative).
   */
  trigger_price?: number;

  /**
   * Units for the trigger price on the secondary orders.
   */
  trigger_price_type?: KrakenWsPriceType;

  /**
   * Deprecated, use trigger_price.
   */
  stop_price?: number;

  /**
   * Display quantity (iceberg-style) for the secondary order.
   */
  display_qty?: number;

  /**
   * Fee preference base or quote currency.
   */
  fee_preference?: KrakenWsFeePreference;

  /**
   * Deprecated, accepted but ignored.
   */
  no_mpp?: boolean;

  /**
   * Self trade prevention mode for secondary orders.
   */
  stp_type?: KrakenWsStpType;

  /**
   * Order volume expressed in quote currency (for buy market orders).
   */
  cash_order_qty?: number;
}

/**
 * Parameters for WS v2 add_order.
 *
 * NOTE:
 * - `token` is optional because `KrakenWebsocketBase` can inject it from
 *   the connection options.
 * - `req_id` is handled by KrakenWebsocketBase.request; do not include it here.
 */
export interface KrakenWsAddOrderParams {
  order_type: KrakenWsOrderType;
  side: KrakenWsOrderSide;
  order_qty: number;
  symbol: string;

  limit_price?: number;
  limit_price_type?: KrakenWsPriceType;
  triggers?: KrakenWsAddOrderTriggers;
  time_in_force?: KrakenWsTimeInForce;
  margin?: boolean;
  post_only?: boolean;
  reduce_only?: boolean;
  effective_time?: string;
  expire_time?: string;
  deadline?: string;
  cl_ord_id?: string;
  order_userref?: number;

  conditional?: KrakenWsAddOrderConditional;

  fee_preference?: KrakenWsFeePreference;
  no_mpp?: boolean;
  stp_type?: KrakenWsStpType;
  cash_order_qty?: number;
  validate?: boolean;
  sender_sub_id?: string;

  /**
   * Deprecated single-field trigger support.
   * Prefer the `triggers` object.
   */
  stop_price?: number;
  trigger?: KrakenWsTriggerReference;

  /**
   * Session token. Optional: if omitted, KrakenWebsocketBase will inject
   * the connection's authToken (when present).
   */
  token?: string;
}

/**
 * Options for addOrder wrapper – maps directly to KrakenWebsocketBase.request.
 */
export interface KrakenWsAddOrderOptions {
  reqId?: number;
  timeoutMs?: number;
  attachAuthToken?: boolean;
}

/**
 * Result payload inside the WS envelope for add_order.
 */
export interface KrakenWsAddOrderResult {
  /**
   * Unique order identifier generated by Kraken.
   */
  order_id: string;

  /**
   * Optional client order ID (cl_ord_id) as sent in the request.
   */
  cl_ord_id?: string;

  /**
   * Optional user reference ID as sent in the request.
   */
  order_userref?: number;

  /**
   * Advisory messages about deprecated fields or upcoming changes.
   */
  warnings?: string[];
}

/**
 * Full WS envelope returned from add_order.
 */
export type KrakenWsAddOrderResponse =
  KrakenWsMethodResponseEnvelope<KrakenWsAddOrderResult>;

/**
 * Send a single new order into the exchange via WS v2.
 *
 * Kraken docs: method = "add_order" (authenticated)
 */
export async function addOrder(
  ws: KrakenWebsocketBase,
  params: KrakenWsAddOrderParams,
  options: KrakenWsAddOrderOptions = {},
): Promise<KrakenWsAddOrderResponse> {
  return ws.request<KrakenWsAddOrderParams, KrakenWsAddOrderResult>(
    'add_order',
    params,
    {
      reqId: options.reqId,
      timeoutMs: options.timeoutMs,
      attachAuthToken: options.attachAuthToken,
    },
  );
}
