import {
  KrakenWebsocketBase,
  KrakenWsMethodResponseEnvelope,
} from '../../../base/websocketBase';
import {
  KrakenWsPriceType,
  KrakenWsTriggerReference,
} from '../../../types/types';
import type {
  KrakenWsOrderSide,
  KrakenWsOrderType,
  KrakenWsTimeInForce,
  KrakenWsAddOrderConditional,
  KrakenWsAddOrderTriggers,
  KrakenWsFeePreference,
  KrakenWsStpType,
} from './addOrder';

/**
 * Single order entry inside a WS v2 batch_add request.
 *
 * All orders in the batch share the same `symbol` (pair), defined at the
 * top-level params.
 */
export interface KrakenWsBatchAddOrderEntry {
  /**
   * Execution side of the order.
   */
  side: KrakenWsOrderSide;

  /**
   * Order type (limit, market, stop-loss, etc.).
   */
  order_type: KrakenWsOrderType;

  /**
   * Order quantity in terms of the base asset.
   */
  order_qty: number;

  /**
   * Order volume expressed in quote currency (market orders only).
   */
  cash_order_qty?: number;

  /**
   * Time-in-force for the order.
   */
  time_in_force?: KrakenWsTimeInForce;

  /**
   * Use margin funding with maximum leverage for the pair (up to 5x).
   */
  margin?: boolean;

  /**
   * Cancels the order if it would take liquidity on arrival.
   * (Limit orders only.)
   */
  post_only?: boolean;

  /**
   * Reduce an existing margin position without opening a larger
   * opposite position.
   */
  reduce_only?: boolean;

  /**
   * Scheduled start time (precision to seconds, RFC3339).
   */
  effective_time?: string;

  /**
   * Expiration time (GTD orders only, RFC3339).
   */
  expire_time?: string;

  /**
   * Fee preference base or quote currency.
   */
  fee_preference?: KrakenWsFeePreference;

  /**
   * Limit price for order types that support it.
   */
  limit_price?: number;

  /**
   * Units for the limit price. Currently only available on trailing-stop
   * / trailing-stop-limit orders.
   */
  limit_price_type?: KrakenWsPriceType;

  /**
   * Deprecated: disables Market Price Protection if true (accepted but ignored).
   */
  no_mpp?: boolean;

  /**
   * Alphanumeric client order identifier (mutually exclusive with order_userref).
   */
  cl_ord_id?: string;

  /**
   * Optional non-unique numeric identifier (mutually exclusive with cl_ord_id).
   */
  order_userref?: number;

  /**
   * For iceberg orders only: quantity to show in the book.
   */
  display_qty?: number;

  /**
   * Self Trade Prevention mode.
   */
  stp_type?: KrakenWsStpType;

  /**
   * Trigger parameters (for triggered order types).
   */
  triggers?: KrakenWsAddOrderTriggers;

  /**
   * Sub-account / trader identifier for enhanced STP.
   */
  sender_sub_id?: string;

  /**
   * Deprecated: use triggers.price / triggers.price_type instead.
   */
  stop_price?: number;

  /**
   * Deprecated: use triggers.reference instead.
   */
  trigger?: KrakenWsTriggerReference;

  /**
   * Conditional template used to generate secondary close orders (OTO).
   */
  conditional?: KrakenWsAddOrderConditional;
}

/**
 * Parameters for WS v2 batch_add.
 *
 * NOTE:
 * - `token` is optional because KrakenWebsocketBase can inject it from
 *   the connection options.
 * - `req_id` is handled by KrakenWebsocketBase.request; do not include it here.
 */
export interface KrakenWsBatchAddParams {
  /**
   * The symbol (pair) for all orders in the batch, e.g. "BTC/USD".
   */
  symbol: string;

  /**
   * A list of orders in the batch.
   * Must contain between 2 and 15 orders (inclusive).
   */
  orders: KrakenWsBatchAddOrderEntry[];

  /**
   * Deadline for the entire batch, in RFC3339 format with millisecond precision.
   * Protects against latency on time-sensitive orders.
   */
  deadline?: string;

  /**
   * If true, validate only; do not trade in the matching engine.
   */
  validate?: boolean;

  /**
   * Session token. Optional: if omitted, KrakenWebsocketBase will inject
   * the connection's authToken (when present).
   */
  token?: string;
}

/**
 * Options for batchAdd wrapper – maps directly to KrakenWebsocketBase.request.
 */
export interface KrakenWsBatchAddOptions {
  reqId?: number;
  timeoutMs?: number;
  attachAuthToken?: boolean;
}

/**
 * Result entry inside the WS envelope for batch_add.
 *
 * The order of these entries matches the order of the orders in the request.
 */
export interface KrakenWsBatchAddOrderResultEntry {
  /**
   * Unique order identifier generated by Kraken.
   */
  order_id: string;

  /**
   * Optional client identifier specified in the batch_add parameters.
   */
  cl_ord_id?: string;

  /**
   * Optional user reference specified in the batch_add parameters.
   */
  order_userref?: number;

  /**
   * Advisory messages about deprecated fields or upcoming changes.
   */
  warnings?: string[];
}

/**
 * Full WS envelope returned from batch_add.
 * `result` is an array of per-order results.
 */
export type KrakenWsBatchAddResponse = KrakenWsMethodResponseEnvelope<
  KrakenWsBatchAddOrderResultEntry[]
>;

/**
 * Send a batch of 2–15 orders in a single WS v2 request.
 *
 * - Validation is performed on the whole batch first; if one order fails
 *   validation, the entire batch is rejected.
 * - On submission, if a specific order fails pre-match checks (e.g. funding),
 *   that order is rejected but the rest of the batch may proceed.
 * - All orders are limited to a single pair, specified by `symbol`.
 *
 * Kraken docs: method = "batch_add" (authenticated)
 */
export async function batchAdd(
  ws: KrakenWebsocketBase,
  params: KrakenWsBatchAddParams,
  options: KrakenWsBatchAddOptions = {},
): Promise<KrakenWsBatchAddResponse> {
  if (!Array.isArray(params.orders) || params.orders.length < 2) {
    throw new Error(
      'Kraken WS batch_add: `orders` must contain at least 2 entries',
    );
  }
  if (params.orders.length > 15) {
    throw new Error(
      'Kraken WS batch_add: `orders` must not contain more than 15 entries',
    );
  }

  for (const [index, order] of params.orders.entries()) {
    if (order.cl_ord_id && typeof order.order_userref === 'number') {
      throw new Error(
        `Kraken WS batch_add: order at index ${index} must not specify both cl_ord_id and order_userref`,
      );
    }
  }

  return ws.request<KrakenWsBatchAddParams, KrakenWsBatchAddOrderResultEntry[]>(
    'batch_add',
    params,
    {
      reqId: options.reqId,
      timeoutMs: options.timeoutMs,
      attachAuthToken: options.attachAuthToken,
    },
  );
}
