import {
  KrakenWebsocketBase,
  KrakenWsMethodResponseEnvelope,
} from '../../../base/websocketBase';
import {
  KrakenWsPriceType,
  KrakenWsTriggerReference,
} from '../../../types/types';

/**
 * Exec type for executions channel events.
 */
export type KrakenWsExecutionType =
  | 'pending_new'
  | 'new'
  | 'trade'
  | 'filled'
  | 'iceberg_refill'
  | 'canceled'
  | 'expired'
  | 'amended'
  | 'restated'
  | 'status';

/**
 * Order status on executions events.
 */
export type KrakenWsOrderStatus =
  | 'pending_new'
  | 'new'
  | 'partially_filled'
  | 'filled'
  | 'canceled'
  | 'expired';

/**
 * Liquidity indicator (maker / taker).
 */
export type KrakenWsLiquidityIndicator = 'm' | 't';

/**
 * Position status for margin orders.
 */
export type KrakenWsPositionStatus = 'opened' | 'closing' | 'closed';

/**
 * Trigger status on triggered orders.
 */
export type KrakenWsTriggerStatus = 'triggered' | 'untriggered';

/**
 * Time-in-force values used on executions stream (upper-case).
 */
export type KrakenWsExecutionTimeInForce = 'GTC' | 'GTD' | 'IOC';

/**
 * Fee entry for trade events.
 */
export interface KrakenWsExecutionFeeEntry {
  /** The fee currency. */
  asset: string;
  /** The fee amount. */
  qty: number;
}

/**
 * Trigger parameters on execution reports (for triggered order types).
 */
export interface KrakenWsExecutionTriggers {
  /** The reference price tracked for triggering orders. */
  reference?: KrakenWsTriggerReference;
  /**
   * Trigger price amount (static or relative), used with `price_type`.
   */
  price?: number;
  /**
   * Units for the trigger price.
   */
  price_type?: KrakenWsPriceType;

  /**
   * Current value of the effective trigger price (after applying relative logic).
   */
  actual_price?: number;

  /**
   * Peak / trough price on trailing-stop / trailing-stop-limit.
   */
  peak_price?: number;

  /**
   * On trigger activation, the value of the reference last price that triggered
   * the order.
   */
  last_price?: number;

  /**
   * Trigger status.
   */
  status?: KrakenWsTriggerStatus;

  /**
   * On trigger activation, the timestamp of the trigger event.
   */
  timestamp?: string;
}

/**
 * Contingent (secondary close order template) information on executions.
 */
export interface KrakenWsExecutionContingent {
  /**
   * Order type of the secondary close orders created on each fill.
   */
  order_type?:
    | 'limit'
    | 'stop-loss'
    | 'stop-loss-limit'
    | 'take-profit'
    | 'take-profit-limit'
    | 'trailing-stop'
    | 'trailing-stop-limit';

  /**
   * Trigger price for secondary orders (triggered types only).
   */
  trigger_price?: number;

  /**
   * Trigger price units for secondary orders.
   */
  trigger_price_type?: KrakenWsPriceType;

  /**
   * Limit price for secondary orders (limit-types only).
   */
  limit_price?: number;

  /**
   * Limit price units for secondary orders.
   */
  limit_price_type?: KrakenWsPriceType;
}

/**
 * Execution report structure for entries in the `executions` channel
 * `data` array.
 *
 * NOTE:
 * - Fields are often conditional based on `exec_type`.
 * - Most are optional here to account for different shapes per event.
 */
export interface KrakenWsExecutionReport {
  // --- Identification / core order fields ---

  /** Unique order identifier generated by Kraken. */
  order_id?: string;

  /** Optional client identifier associated with the order. */
  cl_ord_id?: string;

  /** Optional numeric, client identifier associated with one or more orders. */
  order_userref?: number;

  /** The symbol of the currency pair (e.g. "BTC/USD"). */
  symbol?: string;

  /** Side of the order. */
  side?: 'buy' | 'sell';

  /** The execution model of the order. */
  order_type?:
    | 'limit'
    | 'market'
    | 'iceberg'
    | 'stop-loss'
    | 'stop-loss-limit'
    | 'take-profit'
    | 'take-profit-limit'
    | 'trailing-stop'
    | 'trailing-stop-limit'
    | 'settle-position';

  /** Describes current state of the order. */
  order_status?: KrakenWsOrderStatus;

  /** Event type, determines what fields are present. */
  exec_type?: KrakenWsExecutionType;

  /** Time of the event. */
  timestamp?: string;

  /** Scheduled start time of the order. */
  effective_time?: string;

  /** Scheduled expiration time of the order. */
  expire_time?: string;

  /** Time-in-force for the order. */
  time_in_force?: KrakenWsExecutionTimeInForce;

  // --- Order quantity / price / margin flags ---

  /** Client order quantity (base asset quantity). */
  order_qty?: number;

  /** Display quantity for iceberg order types. */
  display_qty?: number;

  /** For iceberg orders, the next display quantity. */
  display_qty_remain?: number;

  /** Limit price (for limit-type orders). */
  limit_price?: number;

  /** Indicates if the order can be funded on margin. */
  margin?: boolean;

  /** Indicates if the execution is on margin. (trade events only) */
  margin_borrow?: boolean;

  /** Indicates a reduce-only order. */
  reduce_only?: boolean;

  /** Indicates a post-only order. */
  post_only?: boolean;

  /** Indicates if the order has market price protection. */
  no_mpp?: boolean;

  /** Position status on margin orders. */
  position_status?: KrakenWsPositionStatus;

  // --- Execution / fill information ---

  /** Order's average fill price. */
  avg_price?: number;

  /** Client order quantity in quote currency (if supplied). */
  cash_order_qty?: number;

  /** Execution identifier (trade events only). */
  exec_id?: string;

  /** Quantity filled in this event (trade events only). */
  last_qty?: number;

  /** Average price in this trade event (trade events only). */
  last_price?: number;

  /** Value of an individual execution (trade events only). */
  cost?: number;

  /** The order cumulative value executed. */
  cum_cost?: number;

  /** The order cumulative executed quantity. */
  cum_qty?: number;

  /** Liquidity indicator, 't' taker, 'm' maker. */
  liquidity_ind?: KrakenWsLiquidityIndicator;

  /** Trade identifier. */
  trade_id?: number;

  /** Indicates if the order has been liquidated by the engine. */
  liquidated?: boolean;

  /** Referral order transaction id that created this order. */
  ord_ref_id?: string;

  // --- Fees ---

  /**
   * The fees paid on this trade event (quote currency currently).
   * Trade events only.
   */
  fees?: KrakenWsExecutionFeeEntry[];

  /** Preferred currency for paying fees (fcib / fciq). */
  fee_ccy_pref?: string;

  /** Total fee paid in USD. */
  fee_usd_equiv?: number;

  // --- Trigger / contingent info ---

  /** Trigger parameters for triggered order types. */
  triggers?: KrakenWsExecutionTriggers;

  /** Template for secondary close orders. */
  contingent?: KrakenWsExecutionContingent;

  // --- Miscellaneous flags / identifiers ---

  /** Indicates if the order has been amended. */
  amended?: boolean;

  /** Indicates if the order has been liquidated. */
  // (already defined as `liquidated`)

  /** Engine / business reason on certain events. */
  reason?: string;

  /** For institutional accounts, identifies trader / sub-account for STP. */
  sender_sub_id?: string;

  /** User/sub-account identifier when `users=all` is used. */
  user?: string;

  /** Optional external partner order id. */
  ext_ord_id?: string;

  /** Optional external partner execution id. */
  ext_exec_id?: string;

  /** Deprecated: cancellation reason. */
  cancel_reason?: string;

  /** Deprecated: stop price (use `triggers`). */
  stop_price?: number;

  /** Deprecated: trigger reference (use `triggers`). */
  trigger?: KrakenWsTriggerReference;

  /** Deprecated: triggered price (use `triggers`). */
  triggered_price?: number;
}

/**
 * Message payload for the `executions` channel (snapshot or update).
 */
export interface KrakenWsExecutionsMessage {
  channel: 'executions';
  type: 'snapshot' | 'update';
  data: KrakenWsExecutionReport[];
  /** Subscription message sequence number. */
  sequence: number;
}

/**
 * Parameters for subscribing to the `executions` channel.
 *
 * NOTE:
 * - `channel` is automatically set to "executions" by the helper.
 * - `token` is optional here; KrakenWebsocketBase can inject it from
 *   the connection options when `attachAuthToken` is true.
 */
export interface KrakenWsExecutionsSubscribeParams {
  /**
   * If true, the last 50 order fills will be included in snapshot.
   * Default: false.
   */
  snap_trades?: boolean;

  /**
   * If true, open orders will be included in snapshot.
   * Default: true.
   */
  snap_orders?: boolean;

  /**
   * If true, all possible status transitions will be sent.
   * If false, only open/close transitions: new, filled, canceled, expired.
   * Default: true.
   */
  order_status?: boolean;

  /**
   * For xstocks: if true, display in terms of underlying equity.
   * Default: true.
   */
  rebased?: boolean;

  /**
   * If true, the rate-limit counter is included in the stream.
   * Default: false.
   */
  ratecounter?: boolean;

  /**
   * Master accounts only:
   * - "all" → events for master and subaccounts (no snapshot).
   */
  users?: 'all';

  /**
   * Deprecated: use `snap_trades`.
   */
  snapshot_trades?: boolean;

  /**
   * Deprecated: use `snap_orders` / `snap_trades`.
   */
  snapshot?: boolean;

  /**
   * Session token. Optional here, base may inject it automatically.
   */
  token?: string;

  /**
   * Index signature to satisfy Record<string, unknown>.
   */
  [key: string]: unknown;
}

/**
 * Options for subscribeExecutions wrapper – mapped to KrakenWebsocketBase.request.
 */
export interface KrakenWsExecutionsSubscribeOptions {
  reqId?: number;
  timeoutMs?: number;
  attachAuthToken?: boolean;
}

/**
 * Result payload inside the subscribe ack envelope for executions.
 * (Kraken’s subscribe ack has a small result body; we keep it generic
 * but always include `channel`.)
 */
export interface KrakenWsExecutionsSubscribeResult {
  channel: 'executions';
  [key: string]: unknown;
}

/**
 * Full WS envelope returned from subscribe (ack) for executions.
 */
export type KrakenWsExecutionsSubscribeResponse =
  KrakenWsMethodResponseEnvelope<KrakenWsExecutionsSubscribeResult>;

/**
 * Subscribe to the `executions` channel (order status + fills for this account).
 *
 * This sends a WS v2 `subscribe` request with `channel: "executions"`.
 * The returned Promise resolves with the subscribe **ack** envelope.
 * Streaming snapshot/update messages will then arrive on the underlying
 * WebSocket and should be routed via your global message handler.
 *
 * @example
 * ```ts
 * // 1) Send subscribe request
 * const ack = await wsClient.userData.executions.subscribe({
 *   snap_trades: true,
 *   snap_orders: true,
 *   order_status: true,
 * });
 *
 * if (!ack.success) {
 *   console.error("executions subscribe error:", ack.error);
 * }
 *
 * // 2) Somewhere in your WS router:
 * ws.onMessage((raw) => {
 *   const msg = JSON.parse(raw);
 *   if (msg.channel === "executions" && (msg.type === "snapshot" || msg.type === "update")) {
 *     const execMsg = msg as KrakenWsExecutionsMessage;
 *     for (const report of execMsg.data) {
 *       console.log("[exec]", report.exec_type, report.order_id, report.order_status);
 *     }
 *   }
 * });
 * ```
 */
export async function subscribeExecutions(
  ws: KrakenWebsocketBase,
  params: KrakenWsExecutionsSubscribeParams,
  options: KrakenWsExecutionsSubscribeOptions = {},
): Promise<KrakenWsExecutionsSubscribeResponse> {
  const body = {
    channel: 'executions' as const,
    ...params,
  };

  return ws.request<typeof body, KrakenWsExecutionsSubscribeResult>(
    'subscribe',
    body,
    {
      reqId: options.reqId,
      timeoutMs: options.timeoutMs,
      attachAuthToken: options.attachAuthToken ?? true,
    },
  );
}

/**
 * Parameters for unsubscribing from the `executions` channel.
 *
 * NOTE:
 * - `channel` is set to "executions" by the helper.
 * - `token` is optional here; base may inject it automatically.
 */
export interface KrakenWsExecutionsUnsubscribeParams {
  token?: string;
  [key: string]: unknown;
}

/**
 * Options for unsubscribeExecutions wrapper.
 */
export interface KrakenWsExecutionsUnsubscribeOptions {
  reqId?: number;
  timeoutMs?: number;
  attachAuthToken?: boolean;
}

/**
 * Result payload inside the unsubscribe ack envelope for executions.
 */
export interface KrakenWsExecutionsUnsubscribeResult {
  channel: 'executions';
  [key: string]: unknown;
}

/**
 * Full WS envelope returned from unsubscribe (ack) for executions.
 */
export type KrakenWsExecutionsUnsubscribeResponse =
  KrakenWsMethodResponseEnvelope<KrakenWsExecutionsUnsubscribeResult>;

/**
 * Unsubscribe from the `executions` channel.
 *
 * This sends a WS v2 `unsubscribe` request with `channel: "executions"`.
 *
 * @example
 * ```ts
 * const ack = await wsClient.userData.executions.unsubscribe();
 *
 * if (!ack.success) {
 *   console.error("executions unsubscribe error:", ack.error);
 * }
 * ```
 */
export async function unsubscribeExecutions(
  ws: KrakenWebsocketBase,
  params: KrakenWsExecutionsUnsubscribeParams = {},
  options: KrakenWsExecutionsUnsubscribeOptions = {},
): Promise<KrakenWsExecutionsUnsubscribeResponse> {
  const body = {
    channel: 'executions' as const,
    ...params,
  };

  return ws.request<typeof body, KrakenWsExecutionsUnsubscribeResult>(
    'unsubscribe',
    body,
    {
      reqId: options.reqId,
      timeoutMs: options.timeoutMs,
      attachAuthToken: options.attachAuthToken ?? true,
    },
  );
}
